<<<<<<< HEAD
# Generated by Django 4.1 on 2022-09-14 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 4.1 on 2022-08-30 07:03

from django.db import migrations, models
>>>>>>> 21a118e6ed0caa28520a683f6e8b2e4c24bfd597


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 21a118e6ed0caa28520a683f6e8b2e4c24bfd597
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='imageupload')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('image', models.ImageField(null=True, upload_to='postImages')),
                ('user', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
>>>>>>> 21a118e6ed0caa28520a683f6e8b2e4c24bfd597
            ],
        ),
    ]
